(function($){"use strict";$(document).ready(function(){$(".animsition").animsition({inClass:'fade-in',outClass:'fade-out',inDuration:1500,outDuration:800,linkElement:'.animsition-link',loading:true,loadingParentElement:'html',loadingClass:'animsition-loading',loadingInner:'',timeout:false,timeoutCountdown:5000,onLoadEvent:true,browser:['animation-duration','-webkit-animation-duration'],overlay:false,overlayClass:'animsition-overlay-slide',overlayParentElement:'html',transition:function(url){window.location.href=url;}});});$('#different-address').on('click',function(){if($('#different-address').is(":checked")){$('.wrap-input-different-address').slideDown();}
else $('.wrap-input-different-address').slideUp();})
var imgLists=$('.img-list-food');for(var i=0;i<imgLists.length;i++){$(imgLists[i]).find('img').on('mouseover',function(){$(this).parent().parent().next().find('.name-food').addClass('name-run');$(this).parent().parent().next().find('.add-line-run').addClass('line-run');$(this).parent().parent().next().next().addClass('price-run');});}
for(var i=0;i<imgLists.length;i++){$(imgLists[i]).find('img').on('mouseout',function(){$(this).parent().parent().next().find('.name-food').removeClass('name-run');$(this).parent().parent().next().find('.add-line-run').removeClass('line-run');$(this).parent().parent().next().next().removeClass('price-run');});}
$(".chose-people").select2();$(".chose-time").select2();$(".chose-sort").select2({minimumResultsForSearch:Infinity});$('.my-calendar').daterangepicker({"singleDatePicker":true,"showDropdowns":true,});var thisInfo=$('.title-info-product.show .show-content-info-product');$(thisInfo).parent().next('.content-info-product').slideToggle(500);$(thisInfo).parent('.title-info-product').toggleClass('bold-title');if($(thisInfo).html()=='+'){$(thisInfo).html('<i class="fa fa-minus" aria-hidden="true"></i>');}
else{$(thisInfo).html('+');}
$('.show-content-info-product').on('click',function(){$(this).parent().next('.content-info-product').slideToggle(500);$(this).parent('.title-info-product').toggleClass('bold-title');if($(this).html()=='+'){$(this).html('<i class="fa fa-minus" aria-hidden="true"></i>');}
else{$(this).html('+');}});var btnPaypal=$('.wrap-icon-pay');var btn_is_active=-1;for(var i=0;i<btnPaypal.length;i++){$(btnPaypal[i]).on('click',function(){if($(this).index()==btn_is_active){$(this).children('.img-color').toggleClass('active');btn_is_active=-1;}
else{for(var i=0;i<btnPaypal.length;i++){$(btnPaypal[i]).children('.img-color').removeClass("active");}
$(this).children('.img-color').toggleClass('active');btn_is_active=$(this).index();}});}
var windowH=$(window).height()/2;$(window).on('scroll',function(){if($(this).scrollTop()>windowH){$("#myBtn").css('display','flex');}else{$("#myBtn").css('display','none');}});$('#myBtn').on("click",function(){$('html, body').animate({scrollTop:0},300);});$('.show-side-menu').on('click',function(){$('.restyle-home-outgrid .wrap-vertcal-menu').css('right','0px');});$('.hide-side-menu').on('click',function(){$('.restyle-home-outgrid .wrap-vertcal-menu').css('right','-16%');});$('.btn-show-menu-mobile').on('click',function(){$(this).toggleClass('is-active');$('.wrap-side-menu').slideToggle();});var arrowMainMenu=$('.arrow-main-menu');for(var i=0;i<arrowMainMenu.length;i++){$(arrowMainMenu[i]).on('click',function(){$(this).next('.sub-menu').slideToggle();$(this).toggleClass('turn-arrow');})}
$(window).resize(function(){if($(window).width()>=1100){if($('.wrap-side-menu').css('display')=='block'){$('.wrap-side-menu').css('display','none');$('.btn-show-menu-mobile').toggleClass('is-active');}
if($('.sub-menu').css('display')=='block'){$('.sub-menu').css('display','none');$('.arrow-main-menu').removeClass('turn-arrow');}}});})
(jQuery);